all:
	g++ -o ../bin/demos_bin/demo_sortIntegers.out demo_sortIntegers.cpp ../src/heapsort.h ../src/heap.h
	g++ -o ../bin/demos_bin/demo_sortStrings.out demo_sortStrings.cpp ../src/heapsort.h ../src/heap.h

